### PR TITLE
feat: include passive views when necessary

### PR DESCRIPTION
**Pull request by ismay**
Closes: https://jira.dhis2.org/browse/DHIS2-10589, closes #438 
Background info: https://jira.dhis2.org/browse/DHIS2-7016

- [x] Update tests
- [x] Verify it's working correctly against #438

Follow up:

- Bug: the customDataProvider hangs when mocking a query that contains duplicate endpoints

### CODE REVIEW

**Comment by ismay** [comment]
@tomzemp I've made some modifications to your PR in https://github.com/dhis2/usage-analytics-app/pull/438, just to make a fit a bit with the existing style. This should still be in line with what you wanted to achieve. Let me know what you think!

**Review by HendrikThePendric — APPROVED** [review]
I've tested this quite thoroughly and everything appears to be working correctly. Using our demo database there are not many differences in the produced values, but upon further inspection I did notice a few values that had increased somewhat.

As for the code: I noticed we're mutating the response data here, but I think in this case that's not a problem, and probably the cleanest solution.

**Comment by tomzemp** [comment]
Thanks @ismay and @HendrikThePendric!

For curiosity's sake, is there a reason you want to repeatedly make the request to `systemSettings` as part of DataStatisticsQuery.js and make requests to `systemSettings` and to get passive dashboard views (regardless of analytical object type) in TopFavoritesQuery.js vs. refactoring the code more to reduce the number of these requests? I'd just like to understand your preferred code style better in case PEPFAR wants to submit another PR that affects this app.

**Comment by HendrikThePendric** [comment]
Hi @tomzemp very good question. The DataEngine will include client side cashing for repeating GET requests at some point in the fairly near future. This implementation is anticipated that behaviour.

**Comment by ismay** [comment]
> Thanks @ismay and @HendrikThePendric!
> 
> For curiosity's sake, is there a reason you want to repeatedly make the request to `systemSettings` as part of DataStatisticsQuery.js and make requests to `systemSettings` and to get passive dashboard views (regardless of analytical object type) in TopFavoritesQuery.js vs. refactoring the code more to reduce the number of these requests? I'd just like to understand your preferred code style better in case PEPFAR wants to submit another PR that affects this app.

Yeah, as Hendrik said, once we have caching built into the app-platform we won't really have to care about duplicate requests anymore. Also, I felt the performance gains of requesting exactly what you need didn't warrant the added complexity. If it becomes a performance problem we can always address it if and when that happens. Until then I prefer prioritizing code simplicity.

**Comment by tomzemp** [comment]
Got it. Sounds good. Thanks for the explanations 👍

**Comment by ismay** [comment]
> Got it. Sounds good. Thanks for the explanations 👍

Sure thing! Thanks for the PR and helping with the jira issues 😊!

**Pull request merged**
