### PR TITLE
feat: include passive views of dashboards if specified [DHIS2-7016]

### PR DESCRIPTION
**Pull request by tomzemp**
This PR makes use of the newly added keyCountPassiveDashboardViewsInUsageAnalytics setting and api/dataStatistics new PASSIVE_DASHBOARD_VIEW eventType. 

PR modifies app to add in these passive dashboards views if keyCountPassiveDashboardViewsInUsageAnalytics is true.

This PR is related to https://github.com/dhis2/dashboard-app/pull/1562 (which updates the Dashboard App to register passive dashboard views)

This change is requested by PEPFAR.

### CODE REVIEW

**Comment by tomzemp** [comment]
Note: I tried to use conditional logic within existing TopFavoritesQuery to determine if request should also retrieve PASSIVE_DASHBOARD_VIEWs (https://github.com/tomzemp/usage-analytics-app/blob/DHIS2-7016/conditional-query/src/components/Queries/TopFavoritesQuery.js#L49-L65), but this did not seem to work with app platform's refetch (i.e. refetch only triggered refetch with the original query, so switching from CHART_VIEW to DASHBOARD_VIEW did not cause passive views to be pulled (and vice versa)). As a result, I broke this out into TopFavoritesQuery and TopDashboardsQuery.

I'd be happy to implement with some other approach if you'd prefer.

**Comment by ismay** [comment]
Hi @tomzemp, thank you for the PR! Is there a jira issue for this change already at https://jira.dhis2.org? If there is, please add a link to it in the top comment, or otherwise feel free to create one at https://jira.dhis2.org.

That way we can integrate it in our planning process, and make sure that everyone who needs to be involved with the change can participate. Thanks!

**Comment by tomzemp** [comment]
@ismay: I have opened a specific ticket to discuss/track changes for usage analytics app (https://jira.dhis2.org/browse/DHIS2-10589). Let me know if you'd like me to update the PR title

**Comment by ismay** [comment]
> @ismay: I have opened a specific ticket to discuss/track changes for usage analytics app (https://jira.dhis2.org/browse/DHIS2-10589). Let me know if you'd like me to update the PR title

Hi @tomzemp, thanks for the heads up. I somehow missed the notification from GH for your comment, but I see Hendrik already taking a look at it. Thanks for creating the issue and we'll take a look!

**Comment by HendrikThePendric** [comment]
Closing this since it was superseded by #453

**Pull request closed without merging**
