### PR TITLE
feat: visualizations replace charts and pivot tables

### PR DESCRIPTION
**Pull request by martinkrulltott**
`pivot tables` and `charts` has been replaced by `visualizations` in Data visualizer and Dashboards. From 2.37, the pivot table app will be dropped along with the corresponding endpoints. This PR consolidates the two previous types in to `visualizations` for the 2.37 release.

Jira: https://jira.dhis2.org/browse/DHIS2-11662

### CODE REVIEW

**Review by HendrikThePendric — COMMENTED** [review]
Changes are looking good. I've pushed commit 3e3f08c6383b751dbf6eb79d066bbec94cf24fcb to resolve the ESLint errors. 

When running the app locally, I noticed a prop-type error about the property `visualizationViews` being undefined. I also so noticed the related fact that the `Visualization` column was not showing any values, not even `0`s. But when I expected the network-tab, I saw that the GET request was in fact requesting the `visualizationViews` field, but the webapi is not returning it.

So my expectation is that these changes are all correct, but it would be nice to see the full working solution.

**Comment by varl** [comment]
If we are dropping support for some DHIS2 versions, we need to change this: https://github.com/dhis2/usage-analytics-app/blob/master/d2.config.js#L8

And note `BREAKING CHANGE` in a commit message so that we release this as a major bump.

This repo is also a continuous delivery repo, so when it is due for review, QA has to approve the PR.

**Comment by varl** [comment]
> Thanks for the review and the comments.
> I've been in touch with @maikelarabori regarding the API. The [current version running on debug/dev](https://debug.dhis2.org/dev/dhis-web-usage-analytics/index.html) uses the following endpoint which returns 0 for all values, so I assume there's a bug on the backend side, which when resolved should hopefully fix both the all zeros and the missing value for `visualizationViews`.
> 
> https://debug.dhis2.org/dev/api/37/dataStatistics?startDate=2021-01-01&endDate=2021-08-25&interval=YEAR&fields=year,month,week,day,mapViews,chartViews,pivotTableViews,eventReportViews,eventChartViews,dashboardViews,dataSetReportViews,totalViews

I am getting an empty array for this query now, does that mean the bug is fixed and this can proceed ?

**Comment by martinkrulltott** [comment]
It seems like the bug is still present. 
Note that the new format for the request should use `visualizationViews` instead of `chartViews,pivotTableViews` , e.g.
https://debug.dhis2.org/dev/api/37/dataStatistics?startDate=2021-01-01&endDate=2021-08-30&interval=YEAR&fields=year,month,week,day,mapViews,visualizationViews,eventReportViews,eventChartViews,dashboardViews,dataSetReportViews,totalViews
Also note that the endDate needs to be quite recent (preferably today's date) to return data, as the db is reset from time to time, wiping out older data.

The url above returns a result, but it contains `<chartViews>0</chartViews>
<pivotTableViews>0</pivotTableViews>` even though `visualizationViews` was requested.

**Comment by martinkrulltott** [comment]
cc @dhis2/team-platform 
https://jira.dhis2.org/browse/DHIS2-11658?focusedCommentId=43504&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-43504

**Comment by varl** [comment]
Thanks @martinkrulltott, we discussed this on the Platform meeting today as well. It's unclear what the short-term fix is, but the PR that removes the end-points was merged today, so I think we have to merge this by extension.

**Review by varl — APPROVED** [review]

**Review by Philip-Larsen-Donnelly — APPROVED** [review]

**Pull request merged**
