### PR TITLE
chore: update ui-core components and app-platform

### PR DESCRIPTION
**Pull request by varl**
The ui-core SelectField relies on an object with the props for `label` and `value` to make a selection, but this application wires itself around a single value from `event.target.value` and uses that value throughout the state. Which _was_ a clean way to handle it, but it is also tightly coupled.

This PR keeps the coupling, but updates all components to the new ui-core ones.

### CODE REVIEW

**Comment by varl** [comment]
Supersedes https://github.com/dhis2/usage-analytics-app/pull/259
Supersedes https://github.com/dhis2/usage-analytics-app/pull/251
Supersedes https://github.com/dhis2/usage-analytics-app/pull/248

**Comment by varl** [comment]
@HendrikThePendric @ismay Any ideas on a semi-quick fix to avoid the deep object picking on value without rewriting much of the application?

**Comment by varl** [comment]
@HendrikThePendric came up with a better structure for it in 7b79cca. Thanks!

**Comment by varl** [comment]
Still some tests to update:

```
Test Suites: 2 failed, 15 passed, 17 total
Tests:       19 failed, 77 passed, 96 total
Snapshots:   38 passed, 38 total
Time:        2.216s
```

Example of test failure:

```
  ● updateFilterAndGetData › creates USAGE_DATA_ERRORED when updateFilterAndGetData is rejected

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

    @@ -1,15 +1,15 @@
      Array [
        Object {
          "payload": Object {
    -       "key": "category",
    -       "value": Object {
    -         "category": Object {
    -           "label": "top favorites",
    +       "key": Object {
    +         "target": Object {
    +           "name": "category",
                "value": "TOP_FAVORITES",
              },
            },
    +       "value": undefined,
          },
          "type": "FILTER_UPDATED",
        },
        Object {
          "payload": undefined,

      195 |             )
      196 |             .then(() => {
    > 197 |                 expect(store.getActions()).toEqual(expectedActions)
          |                                            ^
      198 |             })
      199 |     })
      200 | })
```

**Comment by HendrikThePendric** [comment]
Hey @varl , a small status update from my side:
- I managed to fix all the tests
- Also refactored the `src/components/FilterFields/index.js` file a bit
- And I also managed to fix the build

So I think this is ready to get merged in now

**Pull request merged**
